# -*- coding: utf-8 -*-
"""
Copy of FINALS

Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1XqFsbpPQ9wxaFk3roW4wEkl7J7oZSDgd
"""

# ==========================================
# Step 1. Import Libraries
# ==========================================
# pandas is used for data manipulation and analysis. It provides the DataFrame object, which is like a virtual spreadsheet.
import pandas as pd

# numpy adds support for large, multi-dimensional arrays and mathematical functions to operate on these arrays.
import numpy as np

# matplotlib.pyplot is a plotting library used to create static, interactive, and animated visualizations in Python.
import matplotlib.pyplot as plt

# seaborn is a data visualization library based on matplotlib. It provides a high-level interface for drawing attractive statistical graphics.
import seaborn as sns

# train_test_split is a function that splits our dataset into two parts: a training set (to teach the model) and a testing set (to evaluate the model).
from sklearn.model_selection import train_test_split

# DecisionTreeClassifier is a machine learning model that makes predictions by learning simple decision rules inferred from the data features (like a flowchart).
from sklearn.tree import DecisionTreeClassifier

# RandomForestClassifier is an ensemble model that fits a number of decision tree classifiers on various sub-samples of the dataset to improve predictive accuracy and control over-fitting.
from sklearn.ensemble import RandomForestClassifier

# accuracy_score calculates the proportion of correct predictions out of all predictions made.
from sklearn.metrics import accuracy_score

# classification_report builds a text report showing the main classification metrics (precision, recall, f1-score) for each class.
from sklearn.metrics import classification_report

# confusion_matrix computes a matrix to evaluate the accuracy of a classification. It shows true positives, true negatives, false positives, and false negatives.
from sklearn.metrics import confusion_matrix

# LabelEncoder is a utility to convert categorical text data (like "High", "Low") into numerical values (like 1, 0) because machine learning models only understand numbers.
from sklearn.preprocessing import LabelEncoder

# ==========================================
# Step 2 & 3. Load Local Dataset
# ==========================================
# Since you are running this locally (not in Google Colab), we cannot use the 'google.colab' module.
# Instead, we read the CSV file directly from your computer using pandas.

# Replace 'movies.csv' with the exact name of the file you want to analyze. 
# Make sure the file is in the same folder as this Python script, or provide the full path to it.
file_name = "movies-dataset-for-feature-extracion-prediction/movies.csv"

try:
    df = pd.read_csv(file_name)
    print(f"Successfully loaded {file_name}")
except FileNotFoundError:
    print(f"Error: Could not find '{file_name}'. Please make sure the file is in the correct folder.")
    exit()

# df.head() displays the first 5 rows of the DataFrame so we can quickly verify the data loaded correctly.
df.head()

# ==========================================
# Step 4. View Dataset Information
# ==========================================
# df.shape returns a tuple representing the dimensionality of the DataFrame (number of rows, number of columns).
print(df.shape)

# df.info() prints a concise summary of the DataFrame, including the column names, non-null counts, and data types (e.g., int, float, object).
df.info()

# ==========================================
# Step 5. Check Duplicate Records
# ==========================================
# df.duplicated() returns a boolean Series (True for duplicate rows). .sum() counts how many 'True' values there are, giving the total number of duplicate records.
duplicates = df.duplicated().sum()

# Prints the total count of duplicate records found in the dataset.
print("Duplicate Records:", duplicates)

# ==========================================
# Step 6. Remove Duplicate Records
# ==========================================
# df.drop_duplicates() removes any rows that are exact duplicates of another row, keeping only the first occurrence. We reassign it back to 'df'.
df = df.drop_duplicates()

# We print the shape again to see how many rows are left after removing the duplicates.
print(df.shape)

# ==========================================
# Step 7. Check Missing Values
# ==========================================
# df.isnull() creates a DataFrame of boolean values indicating missing data (NaN). .sum() counts the missing values for each column.
df.isnull().sum()

# ==========================================
# Step 8. Remove Missing GENRE
# ==========================================
# df.dropna() removes rows that contain missing values. subset=['GENRE'] tells it to only drop the row if the 'GENRE' column specifically is missing data.
df = df.dropna(subset=['GENRE'])

# ==========================================
# Step 9. Fill Missing Numerical Values Using Median
# ==========================================
# select_dtypes(include=np.number) selects only the columns that contain numbers. .columns gets the names of those columns.
numeric_columns = df.select_dtypes(include=np.number).columns

# We loop through every numeric column name we just found.
for col in numeric_columns:
    # df[col].median() calculates the middle value of the column. fillna() replaces any missing values (NaN) in that column with the median. inplace=True modifies the original DataFrame.
    df[col].fillna(df[col].median(), inplace=True)

# We check for missing values again to confirm they have all been handled.
df.isnull().sum()

# ==========================================
# Step 10. Encode GENRE
# ==========================================
# We initialize the LabelEncoder object, which we imported earlier.
encoder = LabelEncoder()

# fit_transform() analyzes the unique text labels in the 'GENRE' column (e.g., "High", "Low"), assigns a number to each (e.g., 0, 1), and replaces the text with those numbers.
df["GENRE"] = encoder.fit_transform(df["GENRE"])

# We display the first 5 rows again to see the newly encoded 'GENRE' column.
df.head()

# ==========================================
# Step 11. Save Cleaned Dataset
# ==========================================
# to_csv() exports the cleaned DataFrame back into a new CSV file named "Cleaned_Dataset.csv". index=False prevents pandas from writing the row numbers as a separate column.
df.to_csv("Cleaned_Dataset.csv", index=False)

# ==========================================
# STEP 12. Exploratory Data Analysis (EDA)
# ==========================================
# df.describe() generates descriptive statistics (mean, count, min, max, standard deviation) for all numerical columns in the dataset.
df.describe()

# --- Distribution of GENRE ---
# plt.figure(figsize=(6,4)) creates a new figure for the plot with a specific width (6 inches) and height (4 inches).
plt.figure(figsize=(6,4))

# sns.countplot() creates a bar chart showing the counts of observations in each categorical bin (in this case, how many times each 'GENRE' appears).
sns.countplot(x='GENRE', data=df)

# plt.title() adds a title to the top of the chart.
plt.title("GENRE Distribution")

# plt.show() renders the plot and displays it on the screen.
plt.show()

# --- Correlation Heatmap ---
# Create a larger figure (10x8 inches) for the heatmap.
plt.figure(figsize=(10,8))

# df.corr() calculates the pairwise correlation of all numerical columns (how strongly they are related from -1 to 1).
# sns.heatmap() plots this correlation matrix as a color-coded grid. annot=True writes the exact correlation number in each square. cmap="coolwarm" sets the color scheme.
sns.heatmap(df.corr(),
            annot=True,
            cmap="coolwarm")

# Add a title to the heatmap.
plt.title("Correlation Matrix")

# Display the heatmap.
plt.show()

# --- Age Distribution ---
# Create a figure for the Age histogram.
plt.figure(figsize=(6,4))

# plt.hist() creates a histogram, which groups the 'Age' data into ranges (bins). bins=20 means the data will be divided into 20 equal-width segments.
plt.hist(df["Age"], bins=20)

# Label the x-axis as "Age".
plt.xlabel("Age")

# Label the y-axis as "Frequency" (how many people fall into that age range).
plt.ylabel("Frequency")

# Add a title to the histogram.
plt.title("Age Distribution")

# Display the histogram.
plt.show()

# --- BMI Distribution ---
# Create a figure for the BMI histogram.
plt.figure(figsize=(6,4))

# Create a histogram for the 'BMI' column, grouped into 20 bins.
plt.hist(df["BMI"], bins=20)

# Add a title to the histogram.
plt.title("BMI Distribution")

# Display the histogram.
plt.show()

# ==========================================
# Step 13. Encode Remaining Categorical Columns
# ==========================================
# df.columns prints a list of all column names currently in the DataFrame.
print(df.columns)

# We import LabelEncoder again (it was already imported at the top, but this ensures it's available here in the Colab notebook flow).
from sklearn.preprocessing import LabelEncoder

# Initialize a new LabelEncoder object named 'le'.
le = LabelEncoder()

# df.select_dtypes(include=['object']).columns finds all columns that contain text data (object type). We loop over each text column.
for column in df.select_dtypes(include=['object']).columns:
    # We convert the column to string type just in case, then fit_transform() replaces the text categories with numerical values, just like we did with GENRE.
    df[column] = le.fit_transform(df[column].astype(str))

# Display the first 5 rows to verify that all text columns have been successfully converted into numbers.
df.head()

# ==========================================
# Step 14. Split Features and Target
# ==========================================
# X (Features) will contain all columns EXCEPT the target we are trying to predict. df.drop() removes the 'GENRE' column from this copy.
X = df.drop(columns=['GENRE'])

# y (Target) will contain ONLY the 'GENRE' column, which is what our machine learning models will learn to predict.
y = df['GENRE']

# Print the shape (rows, columns) of our Features array.
print("Features Shape:", X.shape)

# Print the shape of our Target array. It will only have rows since it's a single column.
print("Target Shape:", y.shape)

# ==========================================
# Step 15. Train-Test Split
# ==========================================
# Import the function to split the data (already imported at top).
from sklearn.model_selection import train_test_split

# train_test_split divides X and y into training sets (for teaching the model) and testing sets (for grading the model).
# test_size=0.20 means 20% of the data is set aside for testing, and 80% is used for training.
# random_state=42 ensures the split is randomly shuffled but in the exact same way every time we run the code (for reproducibility).
# stratify=y ensures that the testing set has the same proportion of different GENREs as the training set, keeping it balanced.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Print how many rows are in the training set (80%).
print(X_train.shape)

# Print how many rows are in the testing set (20%).
print(X_test.shape)

# ==========================================
# Step 16. Decision Tree Modeling
# ==========================================
# Import the Decision Tree model (already imported at top).
from sklearn.tree import DecisionTreeClassifier

# Initialize the model object. random_state=42 ensures the tree builds itself the same way every time.
dt = DecisionTreeClassifier(random_state=42)

# dt.fit() is where the actual learning happens! The model looks at X_train (the features) and y_train (the answers) and learns the rules to connect them.
dt.fit(X_train, y_train)

# ==========================================
# Step 17. Decision Tree Prediction
# ==========================================
# Now that the model is trained, we give it X_test (features it has never seen before) and ask it to predict the GENREs. We save these predictions in 'dt_prediction'.
dt_prediction = dt.predict(X_test)

# ==========================================
# Step 18. Decision Tree Accuracy
# ==========================================
# Import the accuracy score function.
from sklearn.metrics import accuracy_score

# We compare y_test (the real answers) against dt_prediction (what the model guessed) to calculate the percentage of correct guesses.
dt_accuracy = accuracy_score(y_test, dt_prediction)

# Print the final accuracy score as a decimal (e.g., 0.85 means 85% accurate).
print("Decision Tree Accuracy:", dt_accuracy)

# ==========================================
# Step 19. Decision Tree Report
# ==========================================
# Import classification_report.
from sklearn.metrics import classification_report

# Prints a detailed report showing Precision (when it guesses a class, how often is it right?), Recall (out of all true instances of a class, how many did it find?), and F1-Score (a balance of precision and recall) for each specific GENRE.
print(classification_report(y_test, dt_prediction))

# ==========================================
# Step 20. Decision Tree Confusion Matrix
# ==========================================
# Import tools for the confusion matrix.
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# confusion_matrix() creates a grid showing exactly where the model got confused (e.g., predicting 'High Risk' when it was actually 'Low Risk').
cm = confusion_matrix(y_test, dt_prediction)

# Create a figure for the matrix visualization.
plt.figure(figsize=(6,5))

# Use seaborn heatmap to draw the matrix. annot=True puts the numbers inside the boxes. fmt='d' formats the numbers as integers. cmap='Blues' colors it in shades of blue.
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

# Label the x-axis as the values the model "Predicted".
plt.xlabel("Predicted")

# Label the y-axis as the "Actual" true values.
plt.ylabel("Actual")

# Add a title to the matrix chart.
plt.title("Decision Tree Confusion Matrix")

# Display the chart.
plt.show()

# ==========================================
# Step 21. Random Forest Modeling
# ==========================================
# Import the Random Forest model. A random forest is basically a collection of many decision trees working together, which usually provides better accuracy.
from sklearn.ensemble import RandomForestClassifier

# Initialize the model. n_estimators=100 tells it to create 100 different decision trees inside the forest. random_state=42 ensures reproducibility.
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train the Random Forest model on the training data.
rf.fit(X_train, y_train)

# ==========================================
# Step 22. Random Forest Prediction
# ==========================================
# Ask the trained Random Forest to predict the GENREs for the test data.
rf_prediction = rf.predict(X_test)

# ==========================================
# Step 23. Random Forest Accuracy
# ==========================================
# Calculate the percentage of correct guesses for the Random Forest model.
rf_accuracy = accuracy_score(y_test, rf_prediction)

# Print the final accuracy score. This is usually slightly higher than the single Decision Tree.
print("Random Forest Accuracy:", rf_accuracy)

# ==========================================
# Step 24. Random Forest Report
# ==========================================
# Print the detailed precision, recall, and f1-score report for the Random Forest.
print(classification_report(y_test, rf_prediction))

# ==========================================
# Step 25. Random Forest Confusion Matrix
# ==========================================
# Create the confusion matrix grid for the Random Forest predictions.
cm = confusion_matrix(y_test, rf_prediction)

# Create a figure for the matrix.
plt.figure(figsize=(6,5))

# Draw the matrix using seaborn. cmap='Greens' colors this one in shades of green to distinguish it from the Decision Tree matrix.
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens')

# Label the axes.
plt.xlabel("Predicted")
plt.ylabel("Actual")

# Add a title.
plt.title("Random Forest Confusion Matrix")

# Display the chart.
plt.show()